"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { createClientId } from "@/lib/client-id";

type State = "READY" | "RECORDING" | "SUBMITTING" | "EVALUATING" | "ERROR";

export function ExamRecorder(props: { attemptId: string; questionId: string; korean: string; position: number; timeLimitSec: number }) {
  const router = useRouter(); const [state, setState] = useState<State>("READY"); const [remaining, setRemaining] = useState(props.timeLimitSec); const [error, setError] = useState<string>();
  const recorder = useRef<MediaRecorder | null>(null); const stream = useRef<MediaStream | null>(null); const chunks = useRef<Blob[]>([]); const holding = useRef(false); const submitted = useRef(false); const key = useRef(createClientId());
  const submit = useCallback(async (blob: Blob) => { if (submitted.current) return; submitted.current = true; setState("SUBMITTING"); const data = new FormData(); data.set("audio", blob, "answer.webm"); data.set("attemptId", props.attemptId); data.set("questionId", props.questionId); data.set("position", String(props.position)); data.set("idempotencyKey", key.current); try { setState("EVALUATING"); const response = await fetch("/api/test/answer", { method: "POST", body: data }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "평가하지 못했습니다."); setState("ERROR"); } }, [props.attemptId, props.position, props.questionId, router]);
  const stop = useCallback(() => { if (recorder.current?.state === "recording") recorder.current.stop(); }, []);
  const start = useCallback(async () => { if (state !== "READY" && state !== "ERROR") return; setError(undefined); setRemaining(props.timeLimitSec); submitted.current = false; key.current = createClientId(); chunks.current = []; try { if (!navigator.mediaDevices || !window.MediaRecorder) throw new Error(); const media = await navigator.mediaDevices.getUserMedia({ audio: true }); stream.current = media; const next = new MediaRecorder(media); recorder.current = next; next.ondataavailable = (event) => { if (event.data.size) chunks.current.push(event.data); }; next.onstop = () => { media.getTracks().forEach((track) => track.stop()); void submit(new Blob(chunks.current, { type: next.mimeType || "audio/webm" })); }; next.start(250); setState("RECORDING"); if (!holding.current) next.stop(); } catch { setError("마이크를 사용할 수 없습니다. 권한과 브라우저 지원을 확인하세요."); setState("ERROR"); } }, [props.timeLimitSec, state, submit]);
  useEffect(() => { if (state !== "RECORDING") return; const timer = window.setInterval(() => setRemaining((value) => { if (value <= 1) { clearInterval(timer); stop(); return 0; } return value - 1; }), 1000); return () => clearInterval(timer); }, [state, stop]);
  useEffect(() => () => { stream.current?.getTracks().forEach((track) => track.stop()); }, []);
  return <section className="recorder-card"><div className="timer-row"><span className={`state-pill ${state.toLowerCase()}`}>{state}</span><strong>{remaining}초</strong></div><div className="timer-track"><span style={{ width: `${remaining / props.timeLimitSec * 100}%` }} /></div><p className="eyebrow">SAY THIS IN ENGLISH</p><h1>{props.korean}</h1><p className="threshold">시험 중에는 점수와 정답이 공개되지 않습니다.</p><button className={`talk-button ${state === "RECORDING" ? "recording" : ""}`} disabled={state === "SUBMITTING" || state === "EVALUATING"} onPointerDown={(event) => { holding.current = true; event.currentTarget.setPointerCapture(event.pointerId); void start(); }} onPointerUp={() => { holding.current = false; stop(); }} onPointerCancel={() => { holding.current = false; stop(); }} onKeyDown={(event) => { if ((event.key === " " || event.key === "Enter") && !event.repeat) { event.preventDefault(); holding.current = true; void start(); } }} onKeyUp={(event) => { if (event.key === " " || event.key === "Enter") { holding.current = false; stop(); } }}><span>🎙</span>{state === "RECORDING" ? "놓아서 답변 제출" : state === "READY" || state === "ERROR" ? "누르고 말하기" : "평가 중…"}</button>{error && <div className="evaluation-result fail"><p>{error}</p><button className="ghost-button" onClick={() => setState("READY")}>다시 녹음</button></div>}</section>;
}
